### ISSUE TITLE
关于EasyGuiShop.openGui权限

### ISSUE THREAD

**Issue by kroazi** [ZhangYang0204/easy-gui-shop#1]
为什么我给加了权限还一直提示我没有权限 我的腐竹权限可以正常打开 但我的另外的号 权限组是build 但我给了权限的还是打不开 提示我没权限
Builder:
    default: false
    permissions: []
    inheritance:
    - default
    - EasyGuiShop.shopNameLength.6
    - EasyGuiShop.EasyGuiShop.openGui
    - EasyGuiShop.shopAmount.4
    - EasyGuiShop.setGoodVaultPrice
    - EasyGuiShop.teleportShopLocationInterval
    - EasyGuiShop.setGoodPlayerPointsPrice
    - EasyGuiShop.setGoodItemPrice

我加一个.* 也说没权限 怎么回事啊

**Comment by ZhangYang0204** [comment]
权限填写得没问题，你试试有没有成功给玩家builder的权限组，你这里写着给的是玩家build权限组而不是builder

**Comment by kroazi** [comment]
是builder权限组 issus能不能发图片 我可以截图给你看 我是默认的组 应该是我打错字了

**Comment by kroazi** [comment]
我设置为admin也不行哦

**Comment by ZhangYang0204** [comment]
权限填错位置了，应该填在permissions下而不是inherience下
